"""create core database tables

Creates the complete Module 3 (Database Layer) schema:
``devices``, ``sensors``, ``sensor_readings`` (converted into a
TimescaleDB hypertable), ``application_logs``, and ``system_events``.

This migration is hand-written rather than autogenerated because
``create_hypertable()`` is a TimescaleDB SQL function call, not
something Alembic's autogenerate can express as an ORM-level
operation.

Revision ID: a78a2883a6ab
Revises:
Create Date: 2026-07-12
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a78a2883a6ab"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _guid_column_type() -> sa.types.TypeEngine:
    """Return the UUID column type used by this migration.

    Mirrors :class:`app.database.types.GUID`: native PostgreSQL
    ``UUID`` when running on PostgreSQL. This migration targets
    PostgreSQL/TimescaleDB exclusively (per this project's stated
    database technology), so no SQLite fallback branch is needed here
    the way :class:`app.database.types.GUID` provides one for tests.

    Returns:
        A PostgreSQL ``UUID`` type descriptor.
    """
    return postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    """Create devices, sensors, sensor_readings, application_logs, system_events."""
    guid = _guid_column_type()
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # ------------------------------------------------------------------
    # devices
    # ------------------------------------------------------------------
    op.create_table(
        "devices",
        sa.Column("id", guid, primary_key=True, nullable=False),
        sa.Column("device_name", sa.String(length=128), nullable=False),
        sa.Column("firmware_version", sa.String(length=64), nullable=True),
        sa.Column(
            "connection_status", sa.String(length=32), nullable=False, server_default="unknown"
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.UniqueConstraint("device_name", name="uq_devices_device_name"),
    )
    op.create_index("ix_devices_device_name", "devices", ["device_name"], unique=True)

    # ------------------------------------------------------------------
    # sensors
    # ------------------------------------------------------------------
    op.create_table(
        "sensors",
        sa.Column("id", guid, primary_key=True, nullable=False),
        sa.Column("sensor_key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("sampling_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("minimum_value", sa.Float(), nullable=True),
        sa.Column("maximum_value", sa.Float(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.UniqueConstraint("sensor_key", name="uq_sensors_sensor_key"),
    )
    op.create_index("ix_sensors_sensor_key", "sensors", ["sensor_key"], unique=True)

    # ------------------------------------------------------------------
    # sensor_readings (hypertable)
    # ------------------------------------------------------------------
    op.create_table(
        "sensor_readings",
        sa.Column("id", guid, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", guid, nullable=False),
        sa.Column("sensor_id", guid, nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column(
            "raw_value",
            postgresql.JSONB() if is_postgres else sa.JSON(),
            nullable=True,
        ),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column(
            "validation_status", sa.String(length=32), nullable=False, server_default="valid"
        ),
        sa.Column("packet_sequence", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id", "timestamp", name="pk_sensor_readings"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensors.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_sensor_readings_timestamp", "sensor_readings", ["timestamp"])
    op.create_index(
        "ix_sensor_readings_device_timestamp", "sensor_readings", ["device_id", "timestamp"]
    )
    op.create_index(
        "ix_sensor_readings_sensor_timestamp", "sensor_readings", ["sensor_id", "timestamp"]
    )

    if is_postgres:
        # Enable TimescaleDB and convert sensor_readings into a
        # hypertable partitioned on `timestamp`. `if_not_exists` makes
        # this safe to re-run; `migrate_data` is irrelevant here since
        # the table is freshly created and empty.
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
        op.execute(
            "SELECT create_hypertable("
            "'sensor_readings', 'timestamp', "
            "if_not_exists => TRUE, "
            "migrate_data => TRUE)"
        )

    # ------------------------------------------------------------------
    # application_logs
    # ------------------------------------------------------------------
    op.create_table(
        "application_logs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("module", sa.String(length=128), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.create_index("ix_application_logs_timestamp", "application_logs", ["timestamp"])

    # ------------------------------------------------------------------
    # system_events
    # ------------------------------------------------------------------
    op.create_table(
        "system_events",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False, server_default="info"),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "context",
            postgresql.JSONB() if is_postgres else sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.create_index("ix_system_events_timestamp", "system_events", ["timestamp"])
    op.create_index("ix_system_events_event_type", "system_events", ["event_type"])


def downgrade() -> None:
    """Drop all tables created by :func:`upgrade`, in dependency order."""
    op.drop_index("ix_system_events_event_type", table_name="system_events")
    op.drop_index("ix_system_events_timestamp", table_name="system_events")
    op.drop_table("system_events")

    op.drop_index("ix_application_logs_timestamp", table_name="application_logs")
    op.drop_table("application_logs")

    op.drop_index("ix_sensor_readings_sensor_timestamp", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_device_timestamp", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_timestamp", table_name="sensor_readings")
    op.drop_table("sensor_readings")

    op.drop_index("ix_sensors_sensor_key", table_name="sensors")
    op.drop_table("sensors")

    op.drop_index("ix_devices_device_name", table_name="devices")
    op.drop_table("devices")
